apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.0.0
      helm:
        releaseName: loki
        values: |
          loki:
            auth_enabled: false
            useTestSchema: true
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: 6.15.0
      helm:
        releaseName: promtail
        values: |
          config:
            clients:
              - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true