apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.0.0
    chart: loki
    helm:
      valueFiles: []
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          useTestSchema: true
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
        singleBinary:
          replicas: 1
          persistence:
            enabled: false
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        promtail:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true