---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.23.2
    helm:
      values: |
        installCRDs: true

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  # ignoreDifferences:
  #   - group: admissionregistration.k8s.io
  #     kind: MutatingWebhookConfiguration
  #     name: cnpg-mutating-webhook-configuration
  #     jqPathExpressions:
  #       - .webhooks[].clientConfig.caBundle
  #   - group: admissionregistration.k8s.io
  #     kind: ValidatingWebhookConfiguration
  #     name: cnpg-validating-webhook-configuration
  #     jqPathExpressions:
  #       - .webhooks[].clientConfig.caBundle

  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - CreateNamespace=true
  #     - Replace=true
  #     - RespectIgnoreDifferences=true
