---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paas-api
  namespace: paas-api
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: paas-api
  template:
    metadata:
      labels:
        app: paas-api
    spec:
      serviceAccountName: paas-api-sa
      imagePullSecrets:
        - name: scr-pull
      securityContext:
        runAsNonRoot: true
      containers:
        - name: api
          image: registry.onstackit.cloud/scr-daniel/paas-api:3de7015
          imagePullPolicy: Always
          env:
            - name: AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: paas-api-auth
                  key: auth_user
            - name: AUTH_PASS
              valueFrom:
                secretKeyRef:
                  name: paas-api-auth
                  key: auth_pass
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: paas-api-auth
                  key: jwt_secret
            - name: JWT_ISSUER
              value: paas-api
            - name: JWT_AUDIENCE
              value: paas-ui
            - name: JWT_TTL
              value: 15m
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          # bonus -> specify mins and max for hpa requests
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
